### ISSUE TITLE
Black Screen after a few evolutions

### ISSUE THREAD

**Issue by FeyrisTan** [Aldo796/BDSP-Randomizers#1]
So first off: this is great!
But the problem I had with the old random evolution every level mod is still present in this (at least for me).

Also it would be cool to have 2 new features added to them at some point:

1.Fully randomize the moveset of the randomized trainer pokemon
2.Make the moveset fit the randomized pokemon since they just use the moveset of the original pokemon which kinda misses the point for what Im going for.

Keep up the good work.

**Comment by Ai0796** [comment]
could you send me when it black screens (which pokemon and level) and also your mods folder?

also
1. We may add that once all moves get parsed (BDSP has z moves and dynamax moves included in the possible moves, we also need to remove useless moves such as splash)
2. Our randomizer should be changing moves to pokemon, could you send your randomize files to see why it won't work?

**Comment by FeyrisTan** [comment]
only mod I have on is this one with all randomized settings on. It is just a black screen. No log or anything. Does not seem to happen to just a specific pokemon. Happens to me when a bunch of pokemon evolve in one go. 
The randomized encounters do have their own specific movesets yes. But not the trainer pokemon. Even if randomized they use the moveset of the original trainer pokemon in that slot .

Edit: Also just happens to 1 Pokemon after a while. The first evolutions go well and then it just stops working at some point.

**Comment by Ai0796** [comment]
New release should fix trainer move problems. Try to see if there's a pattern for evolution crashes, otherwise we don't know what the problem is.

**Comment by FeyrisTan** [comment]
Well there is not really a pattern. Im just guessing that the randomizer is bugged. This same issue happened with the one
already on gamebanana. I think some evolution infos are just missing and when its evolution time the game does not have the necessary information and just blacks out. idk. Tried on both 1.1.1 and 1.1.0.

So evertime it the game gets stuck I have to re-randomize and add the mod and then it works again for a random amount of time just to get stuck again.

**Comment by FeyrisTan** [comment]
For anybody else having this problem:

I never got it fixed. So it just really seems to be broken right now. BUT. You can use CraftyBoss' randomizer. Its loaded via exefs and overwrites the evolution changes this mod does. Both work together (only on 1.1.0 tho).
