### ISSUE TITLE
Error when randomizing, abilities and field items arent randomized

### ISSUE THREAD

**Issue by leoperes2** [Aldo796/BDSP-Randomizers#10]
Abilities Loaded.
Abilities Randomized.
Abilities Saved.
Field Items Loaded.
An Error has occured: 
<class 'KeyError'>
<class 'tuple'>
<class 'KeyError'>

everything checked but the coming soon, the lockes, utilities and evolution, shops, tm compat.

got this error, the starters are randomized, encounters too, but the abilities and field itens arent randomized.

i downloaded the version 2.4.2 and i'm using BD 1.1.1.

i dumped the romfs using yuzu.

**Comment by Ai0796** [comment]
go back to using version 2.4.1 for now

**Comment by Ai0796** [comment]
Try using the newest version of the randomizer
