### ISSUE TITLE
random starters not working in game

### ISSUE THREAD

**Issue by moonakasoulieheart** [Aldo796/BDSP-Randomizers#12]
I am able to randomize the starters but when I enter the game and pick my starter it shows different names as it should but when i click on it and enter the battle with the starly it is the original starter not the randomized one. Any way to fix it or is it not possible to work yet?

**Comment by Ai0796** [comment]
what randomizer version are you using?
Also what version and game are you playing on?

**Comment by dat1guy2** [comment]
I am also having this problem. I have the newest randomizer and brilliant diamond 1.0.0

**Comment by moonakasoulieheart** [comment]
> what randomizer version are you using?
> Also what version and game are you playing on?

It was the 2.6.0 using shining pearl version 1.1.2

**Comment by AEmmz** [comment]
Also seeing the same issue. Trying to trouble shoot a bit. 

Names fully randomized but the dispatched 'mon is a standard starter. 

I have also tried to run different versions of the software (2.4-2.6) with the same results, leading me to believe that those that are having the issues must be implementing it incorrectly in some way.

@dat1guy2 did you initially start at 1.0.0 or did you downgrade back to 1.0.0 to try to utilize the mod. Curious if your system remembering the 1.1.2 version is the problem here and not the tool at all.

**Comment by moonakasoulieheart** [comment]
I am now using the version for the 1.1.3 as I have dumped it with the 1.1.3 update and starters are still not randomizing using the 2.6.5 version

**Comment by Ai0796** [comment]
Try using the new 2.7 update

**Comment by Icehawk78** [comment]
Following up on this - I've just tried this with Randomizer 2.7 and BD 1.1.3 (with no previous versions ever run on my switch), and I'm still seeing the same issue described above; the starter displays the model of the non-randomized starters while showing the name of the randomized starters. However, upon selection, it reverts back to the normal starter.

The rest of the game does appear to still be randomized. I've tried with the 60FPS mod both on and off, and that doesn't appear to make a difference.

**Comment by moonakasoulieheart** [comment]
I will try the new 2.7 version when I get my laptop back and try putting the exefs stuff from the folder into a exefs folder I will make in the switch atmosphere content of the game itself and let you know how it goes

**Comment by Lieucyan** [comment]
Followed the guide to best of my ability with both yuzu and the game fully updated and 2.7 and still no dice on the starters. Fresh save of the game, too.
Also it's now producing multiple IPS files in exefs, where it was producing text before.

**Comment by Ai0796** [comment]
multiple IPS files should be correct, are you running Pearl?

We have only tested it on Diamond as it's the only version we have
