### ISSUE TITLE
Trainer Battles Not Being Randomized

### ISSUE THREAD

**Issue by SSjGKing** [Aldo796/BDSP-Randomizers#13]
On the Randomizer option, I choose every single option except randomize evolutions, but it still does not randomize the trainer battles. Everything else works fine, but trainer battles never get randomized.

**Comment by Ai0796** [comment]
Are you using any other mods? True Size, Fast Follower, etc.

**Comment by GabrielDena** [comment]
I was having the same issue, just had to deactivate the following speed fix mod.

**Comment by Ai0796** [comment]
both files overwrite masterdatas, what you can do is in the 'mods' folder, replace masterdatas with the following speed mod masterdatas, then randomize the trainers.
