### ISSUE TITLE
I can't randomise the starters

### ISSUE THREAD

**Issue by Max094Reikeb** [Aldo796/BDSP-Randomizers#15]
Hi! I'm testing out this randomiser... I did everything right according to the instructions, the game launches, ... but there's an issue : I'm in-game and nothing is randomized... I'm using latest version for 1.1.3 version of BDSP.

**Comment by SSjGKing** [comment]
it only works for 1.1.1 version of BDSP

**Comment by Max094Reikeb** [comment]
Then why this?
> Changed asset finding code, Should only work on version 1.1.3. if you're using any version below 1.1.3 use the previous randomizer versions

**Comment by Max094Reikeb** [comment]
Nevermind, I just forgot to get the required files that the randomiser changes...
However, the starters stay the same, they can't be randomised even if I check the box in the software to randomise them.

**Comment by Ai0796** [comment]
We're aware of this issue, as there are multiple issues with the same problem I'm closing this thread
