### ISSUE TITLE
Trainers not randomizing properly in 1.1.1

### ISSUE THREAD

**Issue by zeraaaaa** [Aldo796/BDSP-Randomizers#17]
Everything else is randomizing fine, and the trainer table seems to be random in masterdatas.

**Comment by Ai0796** [comment]
Are you using any other mods? True size and others break trainer random as it overwrites the files

**Comment by zeraaaaa** [comment]
ahhh that was the issue! thanks so much
is there any way to get true scale working with random trainers, or is that just not possible?

**Comment by Ai0796** [comment]
not possible unless you want to merge them
