### ISSUE TITLE
Black screen during lake of rage broadcast.

### ISSUE THREAD

**Issue by sora1614** [Aldo796/BDSP-Randomizers#18]
So I randomized my game and got through the part where I name myself and my rival but then I enter a black screen and get stuck. The music is still playing in the background though.

**Comment by sora1614** [comment]
I fixed this issue but now I've got another one. Updated to 1.1.3 and I'm now using the latest randomizer but when I get into the game and reach the menu to pick the language it freezes and I can't progress.

**Comment by Ai0796** [comment]
Did you redump the game?

ILCA changes files every update and 1.1.2 randomized romfs will most likely break on 1.1.3, the same applies to any change in versions.

**Comment by sora1614** [comment]
yes. I redumped it several times.

**Comment by Ai0796** [comment]
are you using any other mods?
