### ISSUE TITLE
Tutorial for Nintendo switch

### ISSUE THREAD

**Issue by Anitek16** [Aldo796/BDSP-Randomizers#19]
hi ive searched all over the internet to find a tutorial to install the randomizer on a switch?

i dont know what to do?

**Comment by Ai0796** [comment]
first you need to dump your romfs onto an SD card using NXdumptool
then with the randomizer, select your romfs folder
from there it'll create a folder called mods
install that like you would install any atmosphere mod on switch

**Comment by noah1gamble** [comment]
> first you need to dump your romfs onto an SD card using NXdumptool then with the randomizer, select your romfs folder from there it'll create a folder called mods install that like you would install any atmosphere mod on switch

I do this with a fresh latest 1.1.3 Brilliant Diamond and get a error, what would I do in such a situation?

**Comment by Anitek16** [comment]
would i install it in atmosphere/contents/0100000011D90000 ?

could i install the randomizer with simple mod manager ?

so i just installed it on atmosphere/contents then the games number but my starter pokemon arnt working it tells me its going to be a different pokemon but then when i throw the pokeball it just sends out the normal starter ??
any reason why?

**Comment by Anitek16** [comment]
and now the game freezes after every dialogue is there a fix for this aswell?

**Comment by Anitek16** [comment]
hello?

**Comment by Ai0796** [comment]
Please create a new issue if you're experiencing a bug different from the title, as it doesn't send me a notification for comments, are you running any other mods by chance, crashing on dialogue is most likely due to an incorrect english
