### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by johnnykf94** [Aldo796/BDSP-Randomizers#2]
Could anyone tell me how set this up with yuzu please? first time using a randomizer with any game. Thank you

**Comment by Ai0796** [comment]
With Yuzu, right click the game press dump romfs then once it finishes it'll open a folder, throw the randomizer in there and then select your randomization settings

then go to Yuzu right click your game and drag the newly created "mods" folder into that, then rename the folder whatever you want to call your mod

**Comment by SSjGKing** [comment]
Is there supposed to be an exefs folder with the romfs because I don't have that.
