### ISSUE TITLE
Game crashes Ryujinx instantly with randomizer mod active

### ISSUE THREAD

**Issue by Nephthyss** [Aldo796/BDSP-Randomizers#20]
Latest version of Ryujinx
Firmware 13.2.0
Pokemon Shining Pearl v1.1.3

It crashes when selecting a language if started with a new save file, and crashes when interacting with anything (speaking with mom after going downstairs for the first time, speaking with the rival when trying to enter his house, and trying to enter the lakefront area)  if using an existing save.

any help would be appriciated and if you need anymore info, let me know

**Comment by Ai0796** [comment]
are you sure you're initial dump was correct, I'd assume something is corrupted with your english file (that's the only one we update)

**Comment by Ai0796** [comment]
Also which randomizers were you using and what does the mod folder look like

**Comment by Nephthyss** [comment]
you mean the RomFS dump? I've just extracted that trough Ryujinx im not sure if that messes something up but its the only way i have to extract XCI's without access to a CFW compatible switch


![2022-01-04 14_27_04-exe win-amd64-3 9](https://user-images.githubusercontent.com/97066587/148065977-eea7b53c-b1c8-43d7-8b3e-195bce47eea2.png)
these are my randomizer settings.
The randomizer is all I have in my mods folder, which includes the RomFS and ExeFS folders I got from the randomizer

**Comment by Ai0796** [comment]
turn off random starters, as exef changes break every update that's the most likely reason it's breaking

**Comment by Nephthyss** [comment]
It works now, thanks for your help! have you thought of making a FAQ somewhere?
