### ISSUE TITLE
Starter Pokemon random error

### ISSUE THREAD

**Issue by scd02** [Aldo796/BDSP-Randomizers#21]
Hello, **Starter Pokemon Random** is available in version 2.2 (BDSP 1.1.1), but **Starter Pokemon** **Random** is not available in later versions.
Can I fix it? Please tell me why it shouldn't work.
Thank you. **Happy New Year**.

**Comment by Ai0796** [comment]
Random starters break on every update and we've decided to wait until ILCA stops updating in order to update it.
