### ISSUE TITLE
Catching Tutorial issue

### ISSUE THREAD

**Issue by inzhainy** [Aldo796/BDSP-Randomizers#25]
This might be a possible Issue.
The randomnised mon killed the bidoof in one hit.
That's fine, then the next battle after this freezes the controls.
And have to reset for it to only happen again.

**Comment by Ai0796** [comment]
I'll look into that could you please tell me 

- The mon that it randomized too 
- The settings you used

**Comment by Ai0796** [comment]
As a temporary fix, go through the catch tutorial with mods off and turn it back on after its done.

**Comment by inzhainy** [comment]
<img width="511" alt="Untitled" src="https://user-images.githubusercontent.com/97492033/148883794-2d8108fc-0a19-4608-a4a5-d0b463886ad3.png">

**Comment by inzhainy** [comment]
And it was Victreebel.
And I had saved after the tutorial aswell.

I probably should have tried disabling and then enabling mods again, but instead I just re-randomized and it worked.

Btw, this program is awesome, tyvm :)
