### ISSUE TITLE
Clear up "Evolution Randomizer" + add "True Evolution Randomizer"

### ISSUE THREAD

**Issue by MegaKBang** [Aldo796/BDSP-Randomizers#27]
Currently the Evolution Randomizer just adds random evolutions at every level for every mon which makes the name of this setting a little misleading imo. Please change it to a more clear name.

Also I'd like to request a "Real Evolution Randomizer" that keeps the method of evolution but just changes the mon that it's going to evolve into.

> ``

**Comment by Ai0796** [comment]
Evolution randomizer has now been changed to evolve using the same method into a random pokemon
