### ISSUE TITLE
Shops randomizer issues

### ISSUE THREAD

**Issue by Senexis** [Aldo796/BDSP-Randomizers#28]
Hey there, this is just a quick post to request some tweaks to the shops randomizer.

## Bugged Items
Currently there's some items in the shop that should be removed as they simply do not work:
- **White Flute:** Costs $0, no texture, description "???";
- **Yellow Flute:** Costs $0, no texture, description "???";
- **Safari Ball:** Costs $0 and therefor cannot be bought;
- **Arceus Plates:** [According to the randomizer](https://github.com/Ai0796/BDSP-Randomizers/blob/55018bdba9679bae4849867828feca21998ab4ad/Randomizers/Shop.py#L33), these should be "useless items" but they are still available?
_I don't think these are useless anyway but was still a little weird._

![2022011815175300-7F4AACC644EAC4BF4E5897B413FFD611](https://user-images.githubusercontent.com/6360733/149954083-a6b3f216-6186-4a9f-9a14-4d687b4eaa2e.jpg)

In general, items with a purchase price of $0 can't be bought as no matter how much money you have it will always say "You don't have enough money."

![2022011815175600-7F4AACC644EAC4BF4E5897B413FFD611](https://user-images.githubusercontent.com/6360733/149954088-087fcb4b-955a-4b47-a9ff-d6a9aa0131a5.jpg)

For convenience, here's all items up to ID 428 (after which all items get ignored in the randomizer) that have a price of $0 and will not be able to be purchased: `0, 1, 5, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134`, though it seems that there are some more that have no price in-game but do have a price in the items table, like the **White Flute**. Possible has to do with the item flag or something.

In addition, here's all items up to ID 428 that have no texture (ID -1) and can be assumed are broken: `0, 113, 114, 115, 120, 129, 130, 131, 132, 133`, the list of items with $0 prices seem to include all of these at first glance.

## Duplicate Items
It seems that quite often one or more items in the shop is duplicated. I feel like duplicated items take away the potential of having a good item. In my run, I didn't get any Pokéballs (except the Safari Ball which can't be bought) in shops until Veilstone which potentially could be prevented by not having duplicates. Even worse, I've had a 3-time duplicate **Yellow Flute** in an earlier run which is especially bad since they are literally useless items that cannot be bought.

If this is not desirable to be the only option, I would at least like to request an option to disable duplicates in shop to make runs a _little_ more feasible and fun.

![2022011815150500-7F4AACC644EAC4BF4E5897B413FFD611](https://user-images.githubusercontent.com/6360733/149953608-18f8fe68-30f6-4826-97e5-6a4158055b78.jpg)

**Comment by Ai0796** [comment]
I'll get on that immediantly, thanks for providing a list to use

**Comment by Ai0796** [comment]
Released a new version it should both remove duplicates and guarantee a pokeball in the first slot

**Comment by Senexis** [comment]
@Ai0796 Thanks for looking into it! I've browsed your changes and have a few comments on that.

First of all you don't need to remove ID 1 (Master Ball) and 5 (Safari Ball) from field items. They should be usable (a little uncertain about the Safari Ball), they are just not buyable from shops due to the $0 price.

Additionally as I mentioned, these IDs don't include all items, including the bugged flutes, it's just what I could easily find from the item files.

Furthermore I would recommend not guaranteeing a Pokeball in the first slot. While it provided a challenge, it is still fun to go out and "hunt" for Pokeballs. Because you get 20 at the start of the game from Dawn/Lucas it's still easily possible to get a good team depending on your luck.

Lastly, it seems the code could be optimized a little. One check, for example, already includes most of the items I listed. It could be good to visit that logic again. If I have some time later I'll try my hand at making the logic there a bit better as well if you can't get to it.

Thanks again! Appreciate all you hard work!
