### ISSUE TITLE
Running/Build error

### ISSUE THREAD

**Issue by FeyrisTan** [Aldo796/BDSP-Randomizers#34]
After doing pip install -r requirements.txt (python 3.8.10,windows)
I try to run main.py and setup.py build.
I can build it ok but it doesnt run neither with main.py or with the actual build:

![main exe](https://user-images.githubusercontent.com/88407761/155894011-1cb631f7-1934-450f-8f2c-9572e9bc277e.png)
![main py](https://user-images.githubusercontent.com/88407761/155894014-b945f632-8e2a-4e2c-a1a7-2df98d04a58d.png)

**Comment by Ai0796** [comment]
The way Red programmed the starter offset finder uses a case statement which was introduced in Python 3.10, you need 3.10 or higher to run it
