### ISSUE TITLE
Starters Not Randomizing

### ISSUE THREAD

**Issue by KorbynThompson** [Aldo796/BDSP-Randomizers#4]
Just a little help is needed. I've tried versions 1.2.0, 1.2.1, and 1.2.2 and I can't get the starters to randomize. Everything else is working fine. In versions 1.2.1 and 1.2.2 the starter names randomize but the Pokemon itself doesn't. Is there a step I missed to make this work?

**Comment by Ai0796** [comment]
Are you running Version 1.1.1 or 1.1.2 of Pokemon BDSP, we haven't officially added support for those versions yet.

**Comment by KorbynThompson** [comment]
Ahhh, yeah. That would be it. Thanks!
