### ISSUE TITLE
So tried to make a rando on the current build got this message, any suggestions?

### ISSUE THREAD

**Issue by RevanXVIV** [Aldo796/BDSP-Randomizers#40]
RomFS Directory set to C:/Users/nickm/Desktop/Pokemon Let's GO SWSH + BDSP Rando/BDSP Rando/updates/v1
Output folder set to C:\Users\nickm\Desktop\Pokemon Let's GO SWSH + BDSP Rando\BDSP Rando\updates\v1\mods
Randomizing Starters!
ERROR: english not found 
An Error has occured: 
Traceback (most recent call last):
  File "main.py", line 54, in buttonClicked
  File "C:\Users\nickm\Desktop\Pokemon Let's GO SWSH + BDSP Rando\BDSP Rando\updates\v1\lib\Randomizers\Starters.py", line 129, in RandomizeStarters
    for obj in env.objects:
AttributeError: 'NoneType' object has no attribute 'objects'

**Comment by RevanXVIV** [comment]
Ok so nevermind this issue, I fixed it after rereading the instructions. Now I want to know where do I put the exefs patches stuff and the two atmosphere files? do both go into the SD card?

**Comment by Ai0796** [comment]
inside atmosphereRandomized is the atmosphere folder which should line up with the atmosphere folder in your SD card, you should be able to copy and paste it directly in
