### ISSUE TITLE
Amount of Pokemon Per Route ?

### ISSUE THREAD

**Issue by Slydee23** [Aldo796/BDSP-Randomizers#54]
Hey, 

I randomized Encounters and thought it replaces every vanilla encounter with always the same randomized Pokemon.

For Example Route 201 has 2 Grass Encounters : Bidoof and Staralili, what i thought that now those 2 are randomized to lets say bidoof got randomized to charmander and staralili to squirtle. But while i was leveling i found like 5-6+ different Pokemon on the same route, so i wanted to ask how does Randomize Encounter actually works

**Comment by Ai0796** [comment]
Every area with encounters has the exact same number of possible spawns (let's say 8, I haven't modded in a while I don't remember off the top of my head.

What the program does is it will randomize each of those slots individually. So route 201 for example has 2 possible encounters, but those two encounter take up 8 slots on the encounter table. Randomization would mix up all 8 encounter slots regardless, making a route that used to only have 2 encounters now have the maximum amount
