### ISSUE TITLE
Character stuck after receiving running shoes 2.4.1, BD v1.1.1

### ISSUE THREAD

**Issue by MesoWRLD** [Aldo796/BDSP-Randomizers#7]
using the 2.4.1 randomizer, PBD v1.1.1, starter state to be randomized by type and pokemon, after picking a random starter and going back home, character just gets stuck after receiving running shoes from mom on switch, in yuzu after receiving running shoes it crashes.

**Comment by MesoWRLD** [comment]
*Update for switch* seems to be an issue with the starters, i re did the randomizer without the starters and everything works fine after getting default starters

**Comment by Ai0796** [comment]
We'll work on fixing that, starters seem to break every update.
