### ISSUE TITLE
UI Doesn't expand

### ISSUE THREAD

**Issue by Crimsonhwkz** [Aldo796/BDSP-Randomizers#8]
UI is jumbled up together, so you cannot read the checkboxes. doesn't change in full screen, on windows 11.

**Comment by SSjGKing** [comment]
Im on Windows 10 and have the same problem. I cant read any of the options since it wont expand. This is what it looks like.
<img width="503" alt="Capture" src="https://user-images.githubusercontent.com/96107390/145953992-30821bb9-c391-40bf-9031-7d27694ac899.PNG">
.

**Comment by Ai0796** [comment]
I've released a new version based on a different UI with scaling, try using that

**Comment by Ai0796** [comment]
Fixed in new update
