### ISSUE TITLE
Character stuck?

### ISSUE THREAD

**Issue by MikeTheQuick** [Aldo796/BDSP-Randomizers#9]
At the start of the game when you meet barry in his room at the top my character freezes. ive been having this issue for the past few updates, im on the newest version of pearl (1.1.2) and i havent updated my switch. Am i doing something wrong?

**Comment by Ai0796** [comment]
What randomizers did you use?

**Comment by MikeTheQuick** [comment]
everything besides evolutions and tm compatability

**Comment by Ai0796** [comment]
I've released a new version with some more sanity checks try that.

**Comment by Ai0796** [comment]
Try turning off shop randomizer, there might be a link to that and freezing during that event

**Comment by MikeTheQuick** [comment]
> Try turning off shop randomizer, there might be a link to that and freezing during that event

i tried with the newest update, still no

**Comment by MikeTheQuick** [comment]
wrong button, sorry

**Comment by thelars0r** [comment]
Had the same problem, tried nearly all different versions. Character was always stuck. Removing the files and adding them after the scene help, but getting the boots was the next stuck point for me.

Today I freshly installed diamond 1.0 and installed a 1.1 nsp (google, should be around 2,5 gigs). Dumped the 1.1 version as romfs and also used the 2.4.2 version of the randomizer. Used all random options except evolution and it worked without problems. Used IPSwitch to get the starters working too.

When I use random field items I get this error in the randomizer:
An Error has occured: 
<class 'KeyError'>
<class 'tuple'>
<class 'KeyError'>
but seems to work anyway...

**Comment by Ai0796** [comment]
We've released a new version of the randomizer with a better error logger. Try using that, if it still spits out an error, post the longer error message here.

**Comment by MikeTheQuick** [comment]
> We've released a new version of the randomizer with a better error logger. Try using that, if it still spits out an error, post the longer error message here.

When i did it, there was no error message, but when i talked to the rival and got my running shoes it froze

**Comment by EchoApeiron** [comment]
I am having the same issue. Have my AMS/OFW fully updated on the Switch. But it seems to only occur when I have Randomize Trainers on. I was able to get a successful rando seed with just the following options:

Starters
Pokemon
Safari
Underground
TMs
Abilities

**Comment by Ai0796** [comment]
Closed as this is a month old
